steps:
  # Build and push backend image
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-backend-service:latest",
        "./backend",
      ]
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-backend-service:latest",
      ]

  # Deploy backend as Cloud Run service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor:
      - "gcr.io/cloud-builders/docker:latest"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "ai-analyst-backend-service",
        "--image=us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-backend-service:latest",
        "--region=us-central1",
        "--platform=managed",
      ]

  # Build and push extract_benchmarking_agent_job image
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/extract-benchmarking-agent-job:latest",
        "./agentic_jobs/extract_benchmarking_agent_job",
      ]
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/extract-benchmarking-agent-job:latest",
      ]

  # Deploy extract_benchmark as Cloud Run job
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor:
      - "gcr.io/cloud-builders/docker:latest"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "jobs",
        "update",
        "extract-benchmark-pitch-agent-job",
        "--image=us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/extract-benchmarking-agent-job:latest",
        "--region=us-central1",
        "--memory=2Gi",
        "--task-timeout=1800s",
        "--max-retries=3",
      ]

  # Build and push frontend image
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-frontend-service:latest"
      - "./frontend"
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-frontend-service:latest"

  # Deploy frontend as Cloud Run service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor:
      - "gcr.io/cloud-builders/docker:latest"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "ai-analyst-frontend-service"
      - "--image=us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-frontend-service:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

  # Build and push ai-to-founder-voice-agent service image
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-to-founder-voice-agent-service:latest"
      - "./agents/ai-to-founder-voice-agent"
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-to-founder-voice-agent-service:latest"

  # Deploy ai-to-founder-voice-agent as Cloud Run service (WebSocket-enabled)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor:
      - "gcr.io/cloud-builders/docker:latest"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "ai-to-founder-voice-agent-service"
      - "--image=us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-to-founder-voice-agent-service:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-backend-service:latest"
  - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/extract-benchmarking-agent-job:latest"
  - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-analyst-frontend-service:latest"
  - "us-central1-docker.pkg.dev/startupevaluator-472213/cloud-run-source-deploy/ai-to-founder-voice-agent-service:latest"

options:
  logging: CLOUD_LOGGING_ONLY
