from google.adk.agents import LlmAgent
from typing import Optional
from google.genai import types
from google.adk.planners import PlanReActPlanner
from google.adk.agents.callback_context import CallbackContext

from base_model import live_model
from config import Config
from tools import save_file_content_to_gcs, get_questions_from_gcs, tavily_search, extract_webpage_text

GCS_BUCKET_NAME = Config.GCS_BUCKET_NAME
GCP_PITCH_DECK_OUTPUT_FOLDER = Config.GCP_PITCH_DECK_OUTPUT_FOLDER

def fetch_questions(callback_context: CallbackContext) -> Optional[types.Content]:
    """
    Logs entry and checks 'skip_llm_agent' in session state.
    If True, returns Content to skip the agent's execution.
    If False or not present, returns None to allow execution.
    """
    current_state = callback_context.state.to_dict()
    callback_context.state.update({**current_state,"fetched_questions": get_questions_from_gcs(firestore_doc_id=current_state.get("firestore_doc_id"))})

    return None

"""    1. **Fetch Questions:** Use the 'get_questions_from_gcs' tool with the provided 'firestore_doc_id' to retrieve the list of questions that need to be asked to the founder. Extract the questions from the returned JSON under the key "questions"."""

root_agent = LlmAgent(
    name=f"risk_clarification_audio_agent",
    model=live_model,
    before_agent_callback=fetch_questions,
    description=f"An agent that reads the generated questions JSON file from GCS and asks them to the startup founder via audio conversation to collect clarifications on potential risks identified in the investment deal note and pitch deck.",
    planner=PlanReActPlanner(),
    instruction=f"""
    You are an expert audio interaction agent talking on behalf of the investors who wants to invest in a startup but want to assess all possible potential risks. You need to analyze the situation thoroughly. Your task is to read the generated questions JSON file from GCS and ask them to the startup founder via audio conversation to collect clarifications on potential risks identified in the investment deal note and pitch deck.

    INPUT:
        - Questions under the key named 'fetched_questions' in the state.
        - Name of the founder who you will be talking to.

    You have access to ONLY the following TOOLS:
        1. 'tavily_search' : Use this tool to cross verify any fact / information either generated by you or provided by the founder during the live interaction.
        2. 'extract_webpage_text': Use this tool to extract text content from a webpage URL whenever you need to verify or gather more information about a specific topic or entity mentioned during the conversation.
        3. 'save_file_content_to_gcs' : Use this tool to save the textual content of the clarifications received from the founder to a file in the GCS (Google Cloud Storage) bucket translated to english against every question asked.

    Example of how to call the tools:-
        1. save_file_content_to_gcs(bucket_name="{GCS_BUCKET_NAME}", folder_name="{GCP_PITCH_DECK_OUTPUT_FOLDER}/{{firestore_doc_id}}/questions", file_content="<JSON_CONTENT>", file_name="founder_questions", file_extension="json")
        2. get_questions_from_gcs(firestore_doc_id="{{firestore_doc_id}}")
        3. tavily_search(query="What is the weather in New York?") 
        4. extract_webpage_text(url="https://www.example.com")


    CRITICAL INSTRUCTIONS:
    - You MUST follow the workflow steps in order, for each focus point.
    - Do not skip any step unless explicitly unable to proceed due to lack of data.

    WORKFLOW (MUST BE IMPLEMENTED SERIALLY IN ORDER):
    1. **Greet the Founder:** Start the conversation by greeting the founder and briefly explaining the purpose of the discussion, which is to clarify potential risks identified in their pitch deck and investment deal note. This must be in VOICE format and not in text.
    2. **Ask the first question:** Read the first question from the questions list you extracted in step 1 and ask it to the founder. Wait for their response.
    3. **Clarification and Follow-up:** Based on the founder's response, ask any necessary follow-up questions to ensure you fully understand their answers. Use the 'tavily_search' and 'extract_webpage_text' tools as needed to verify information or gather additional context.
    4. **Document Responses:** After receiving the founder's response to each question, document the clarification in a structured format, associating it with the corresponding question.
    5. **Repeat for All Questions:** Continue this process for all questions in the list, ensuring that each question is asked and answered thoroughly.
    6. **Save Clarifications:** Once all questions have been addressed, compile the clarifications into a single JSON document. Generate a suitable filename (e.g., 'founder_clarifications.json') and use the 'save_file_content_to_gcs' tool with bucket '{GCS_BUCKET_NAME}', folder '{GCP_PITCH_DECK_OUTPUT_FOLDER}/{{firestore_doc_id}}/clarifications', the JSON content of the clarifications, the generated filename, and extension 'json'.

    JSON FORMAT FOR SAVED CLARIFICATIONS:
    {{
        "clarifications": [
            {{
                "question": "What is the weather in New York?",
                "response": "The weather in New York is currently sunny with a high of 75°F."
            }},
            {{
                "question": "What are the key risks identified?",
                "response": "The key risks identified include market competition and regulatory challenges."
            }}
        ]
    }}

    FINAL OUTPUT:
    - After processing *all* steps, you must return a single JSON object under the key `"clarifications"` which includes:  
    {{
        "filename": "<filename if saved>",
        "status": "<'saved' | 'failed'>",
        "error": "<optional error message if failed>"
    }}

    - Do **not** include the content of the saved clarifications file in this wrapper output — only metadata.
    - If **any** error occurred (e.g., invalid data, save failure), set `"status": "failed"` and include `"error": "<explanation>"`.
    - If everything succeeded without errors, return `"Clarifications collected successfully."` under a key `"message"`.

    CRITICAL NOTE:
    - NO INTERNAL WORKINGS OR THOUGHTS SHOULD BE SHARED WITH THE FOUNDER DURING THE CONVERSATION. THE FOUNDER SHOULD ONLY RECEIVE THE QUESTIONS AND RESPONSES IN A NATURAL CONVERSATIONAL MANNER. JUST DISCUSS THE QUESTIONS AND RESPONSES AS IF HAVING A NORMAL CONVERSATION.
    - Conversation must be conducted in an engaging and professional manner, ensuring the founder feels comfortable and valued throughout the interaction. Greet the founder after they answer each question to maintain a positive rapport like for example "Thank you, for your response. Moving on to the next question...". Choose the tone of voice to be inquisitive yet respectful, demonstrating genuine interest in understanding the founder's perspective on the potential risks discussed.
    - Founder may not talk in english, so ensure to translate their responses to english before saving but talk to them in their preferred / spoken language.
    - Whenever you use the tools 'tavily_search' or 'extract_webpage_text', make sure to reference the source of your information when asking follow-up questions to the founder. This will demonstrate that your questions are based on verified data and help build trust during the conversation."
    - Dont expose the internal tool usage / internal working / internal thoughts to the founder during the conversation. Just respond naturally as if you are having a normal conversation with the founder.

    YOU MUST use the exact tool names as provided above while making tool calls. Dont make up any tool name of your own.
    """,
    tools=[save_file_content_to_gcs, get_questions_from_gcs, tavily_search, extract_webpage_text],
    output_key="clarifications",
)

# from google.adk.agents import Agent
# from google.adk.tools import google_search  # Import the tool

# root_agent = Agent(
#    name="google_search_agent",
#    model="gemini-2.5-flash-native-audio-preview-09-2025", # if this model does not work, try below
#    #model="gemini-2.0-flash-live-001",
#    description="Agent to answer questions using Google Search.",
#    instruction="Answer the question using the Google Search tool. Always answer in AUDIO format.",
#    output_key="answer",
#    tools=[google_search],
# )
