"""
    This file contains the benchmarking focus points that each data extraction agent will work upon.

    Created By:- Arnab Ghosh (https://github.com/ARNABGHOSH123)
"""

focus_points = [
    """- **Market Position**: How does the startup's market size and growth compare to competitors?""",
    """- **Team member profiling**: Profile the team members. Link their valid LinkedIn / valid available business profile and provide their work details.""",
    """- **Team Strength**: How does the experience and background of the startup's team compare to competitors?.""",
    """- **MOAT Analysis**: What are the startup's competitive advantages and barriers to entry?""",
    """- **USP**: What is the startup's Unique Selling Proposition and how does it stand out in the market? (2-3 points)""",
    """- **Funding Analysis**: What are the details of the startup's funding rounds? (date, amount, investors, valuation, etc.) Example: Crowdfunding - 12th Dec 2023 - $1M - Lead investor - Sequoia Capital India, Valuation - $10M, etc. Funding details must be in tabular format along with dates. Include total funding amount raised to date.""",
    """- **Vision**: What is the startup's vision and long-term goals?""",
    """- **Currently Active Investors**: Who are the current active investors in the startup? (name, type, investment date, amount, etc.)""",
    """- **Traction**: How does the startup's traction (e.g., user growth, revenue) compare to competitors?""",
    """- **Financial Health**: What is the financial status of the startup compared to its competitors?""",
    """- **Competitive Landscape**: Who are the main competitors and what are their strengths and weaknesses?""",
    """- **Industry Trends**: What are the current trends in the industry that may impact the startup's success?""",
    """- **Founder Background**: Evaluate the founders' previous experience and successes in the industry. Reveal their educational background, work experience, technical expertise and any notable achievements. It should be detailed.""",
    """- **Product Differentiation**: Analyze how the startup's product or service stands out from competitors""",
    """- **Earning Call Summaries**: If available, analyze recent earning call summaries of public competitors to gauge market sentiment and performance.""",
    """- **User Base Evaluation**: Assess the size and engagement level of the startup's user base compared to its competitors.""",
    """- **SWOT Analysis**: Conduct a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for the startup based on the extracted information and web search findings.""",
    """- **Risk Assessment**: Identify potential risks and challenges the startup may face in the current market landscape. Detail these risks and suggest possible mitigation strategies. Consider inconsistent metrics, inflated market size, or unusual churn patterns.""",
    """- **Future Outlook**: Provide insights into the startup's future prospects based on current data and market trends.""",
    """- **Business KPIs**: Identify and analyze key performance indicators relevant to the startup's business model and industry such as customer acquisition cost, lifetime value, churn rate, and monthly recurring revenue, and compare them with industry benchmarks.""",
    """- **Regulatory Environment**: Consider any regulatory factors that may impact the startup's operations and growth potential.""",
    """- **Customer Feedback**: If available, analyze customer reviews and feedback to gauge market reception and areas for improvement.""",
    """- **Technology Stack**: Evaluate the startup's technology stack and its scalability compared to competitors.""",
    """- **Partnerships and Alliances**: Identify any strategic partnerships or alliances that may enhance the startup's market position.""",
    """- **Market Challenges**: Identify any significant challenges in the market that could impact the startup's growth and suggest strategies to overcome them.""",
    """- **Innovation and R&D**: Assess the startup's commitment to innovation and research and development compared to competitors.""",
    """- **Marketing Strategy**: Analyze the startup's marketing and customer acquisition strategies in comparison to its competitors.""",
    """- **Operational Efficiency**: Evaluate the startup's operational processes and efficiency compared to industry standards.""",
    """- **Sustainability Practices**: Consider the startup's sustainability and corporate social responsibility practices in comparison to competitors.""",
    """- **Exit Opportunities**: Analyze potential exit opportunities for the startup, such as acquisitions or IPOs, based on market trends and competitor activities.""",
    """- **Industry Reports**: Find relevant industry reports that provide insights into market trends and competitive analysis and provide their links.""",
    """- **News Articles**: Find recent news articles about the startup and its competitors and their respective sectors and geographies and provide their links.""",
    """- **Social Media Analysis**: Find social media posts and discussions about the startup and its competitors and provide their links.""",
    """- **Technology Reports**: If applicable, analyze technology reports to understand the startup's technological edge or gaps compared to competitors or as per the sector. Provide curated links to these reports and one line description.""",
    """- **Competitor Analysis**: Provide the competitive analysis in a tabular format comparing key metrics of the startup and its main competitors. Competitors should be segregated geography wise. If the company is Indian, try to list down Indian competitors first and then global competitors. Include columns for metrics such as market share, team size, funding, user base, headquarters, description, founded year, last round, last raised, total raised, status (private/public), detailed offerings and features, USP, B2B/B2C, Target Market, Key Clients, Growth Market (Sales-led/Self-serve), domain url, and any other relevant KPIs.""",
    """- **Market Sentiment**: Analyze market sentiment towards the startup and its competitors using recent news, social media, and analyst reports. Provide links to relevant sources.""",
    """- **Fundraising Environment**: Consider the current fundraising environment and how it may impact the startup's ability to raise future capital.""",
    """- **Regulatory Changes**: Stay updated on any regulatory changes that could affect the startup's industry and operations.""",
    """- **Talent Acquisition**: Evaluate the startup's ability to attract and retain top talent compared to its competitors.""",
    """- **Customer Acquisition Channels**: Analyze the effectiveness of the startup's customer acquisition channels compared to competitors.""",
    """- **Market Expansion Plans**: Consider the startup's plans for market expansion and how they compare to competitors.""",
    """- **Northstar Metrics Evaluation**: Identify the startup's northstar metrics and evaluate their effectiveness in driving growth and engagement in its respective sector.""",
    """- **Valuation and Buyers**: If available, analyze the startup's current valuation and potential buyers in the market. Provide insights into how this positions the startup for future growth and investment opportunities. Provide links if you find such information."""
]
